#!/bin/bash

TIME=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
VALUE=$RANDOM

API="http://localhost:8000/api/v1/cosm"
COSM_ID=$1

echo usage cosm_stream ID NUM_MESSAGES INTERVAL_SECONDS

for (( i=1; i<=$2; i++ ))
do
	echo Sending $i
	curl --dump-header - -H 'Content-Type: application/json' -X POST --data @- $API/$COSM_ID/ <<END_DOC
{
  "environment": 
  {
    "description": "",
    "feed": "http:\/\/api.cosm.com\/v2\/feeds\/343",
    "id": 343,
    "location": 
    {
      "lat": 55.74479,
      "lng": -3.18157,
      "name": "location description"
    },
    "title": "test feed yes"
  },
  "id": 1,
  "threshold_value": 9.0,
  "timestamp": "$TIME",
  "triggering_datastream": 
  {
    "id": "0",
    "url": "http:\/\/api.cosm.com\/v2\/feeds\/343\/datastreams\/0",
    "at": "2009-09-07T12:16:02.000063Z",
    "value": 
    {
      "current_value": "$RANDOM",
      "max_value": 9.99650150341,
      "min_value": 0.00471012639984
    }
  },
  "type": "gte",
  "url": "http:\/\/api.cosm.com\/v2\/triggers\/1"
}
END_DOC

	sleep $3
done