#!/bin/bash

PREAMBLE=""
API="http://localhost:8000/api/v1"
function PUT 
{
	echo "curl $PREAMBLE PUT --data '$2' $API/$1"
	curl --dump-header - -H 'Content-Type: application/json' -X PUT --data "$2" $API/$1
}
function PUTF
{
	echo curl $PREAMBLE PUT --data @- $API/$1 < $2
	curl --dump-header - -H 'Content-Type: application/json' -X PUT --data @- $API/$1 < $2
}

function PATCH 
{
	echo "curl $PREAMBLE PATCH --data '$2' $API/$1"
	curl --dump-header - -H 'Content-Type: application/json' -X PATCH --data "$2" $API/$1
}
function PATCHF
{
	echo curl $PREAMBLE PATCH --data @- $API/$1 < $2
	curl --dump-header - -H 'Content-Type: application/json' -X PATCH --data @- $API/$1 < $2
}


function POST 
{
	curl --dump-header - -H 'Content-Type: application/json' -X POST --data "$2" $API/$1
}
function POSTF
{
	curl --dump-header - -H 'Content-Type: application/json' -X POST --data @- $API/$1 < $2
}

function GET
{
	curl --dump-header - -H 'Content-Type: application/json' -X GET http://localhost:8000/api/v1/$1
}

echo "Now you can do:"
echo "PUT datastore/1/ '[1,1],[2,2]'"
echo "PUTF datastore/1/ resources/input.json"
echo "POST datastore/1/ '[1,1],[2,2]'"
echo "GET datastore/1/"
echo "(don't forget the trailing slash)"
